export {
  curriculumClient,
  isCurriculumApiAvailable,
  isCurriculumAuthReady,
  setCurriculumAuthToken,
  clearAuthToken,
  fetchCurriculumTree,
  fetchUnitBySlug,
  fetchLessonBySlug,
  fetchLessonById,
  createUnit,
  updateUnit,
  deleteUnit,
  reorderUnits,
  createTopic,
  updateTopic,
  deleteTopic,
  moveTopic,
  reorderTopics,
  createLesson,
  saveLessonDraft,
  publishLesson,
  deleteLesson,
  moveLesson,
  reorderLessons,
  updateLessonAuthoring,
  listLessons,
  syncManifest,
  exportManifest,
  fetchLessonDrafts,
} from '@monte/api';

export type {
  CurriculumClient,
  CurriculumTree,
  CurriculumTreeLesson,
  CurriculumTreeTopic,
  CurriculumTreeUnit,
  LessonDraftRecord,
  CurriculumManifest,
  CurriculumSyncSummary,
  LessonAuthoringUpdate,
} from '@monte/api';

