import { createHash } from "node:crypto";
import { access, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import {
  getZodClientTemplateContext,
  maybePretty,
} from "openapi-zod-client";
import type {
  OpenAPIObject,
  OperationObject,
  ParameterObject,
  PathItemObject,
  ReferenceObject,
  RequestBodyObject,
} from "openapi3-ts";
import { parse as parseYaml } from "yaml";

import { loadTimebackEnv } from "../src/env";

type Service = "qti" | "oneroster" | "caliper" | "powerpath";

type ServiceGenerationConfig = {
  specEnvironment: "staging" | "production";
};

type GenerationResult = {
  service: Service;
  status: "generated" | "skipped" | "failed";
  message?: string;
};

type OperationMetadata = {
  pathTemplate: string;
  parameters: Map<string, ParameterRequirement>;
  body?: OperationBodyMetadata;
};

type ParameterRequirement = {
  required: boolean;
};

type OperationBodyMetadata = {
  required: boolean;
  contentTypes: ReadonlyArray<string>;
  description?: string;
};

type TemplateContext = ReturnType<typeof getZodClientTemplateContext>;

type ServiceTypePrefix = {
  caliper: "Caliper";
  oneroster: "OneRoster";
  powerpath: "Powerpath";
  qti: "Qti";
};

const SPEC_DIR = fileURLToPath(new URL("../openapi", import.meta.url));
const SRC_DIR = fileURLToPath(new URL("../src", import.meta.url));
const FILE_HEADER =
  "// This file is auto-generated by scripts/generate.ts. Do not edit manually.\n";

const SERVICE_CONFIG: Record<Service, ServiceGenerationConfig> = {
  qti: { specEnvironment: "staging" },
  oneroster: { specEnvironment: "staging" },
  caliper: { specEnvironment: "staging" },
  powerpath: { specEnvironment: "staging" },
};

const SERVICE_TYPE_PREFIX: ServiceTypePrefix = {
  caliper: "Caliper",
  oneroster: "OneRoster",
  powerpath: "Powerpath",
  qti: "Qti",
};

const HTTP_METHODS = [
  "get",
  "put",
  "post",
  "delete",
  "options",
  "head",
  "patch",
  "trace",
] as const;

async function main() {
  loadTimebackEnv();

  const results: GenerationResult[] = [];

  for (const service of Object.keys(SERVICE_CONFIG) as Service[]) {
    const result = await generateForService(service, SERVICE_CONFIG[service]);
    results.push(result);
  }

  for (const result of results) {
    const base = `[${result.service}]`;
    const message = result.message ? ` ${result.message}` : "";
    process.stdout.write(`${base} ${result.status}${message}\n`);
  }

  const failures = results.filter((result) => result.status === "failed");
  if (failures.length > 0) {
    process.exitCode = 1;
  }
}

async function generateForService(
  service: Service,
  config: ServiceGenerationConfig,
): Promise<GenerationResult> {
  const specPath = join(SPEC_DIR, service, `${config.specEnvironment}.yaml`);

  if (!(await fileExists(specPath))) {
    return {
      service,
      status: "failed",
      message: `Spec not found for ${config.specEnvironment} (${specPath})`,
    };
  }

  const outputDir = join(SRC_DIR, service, "generated");
  await mkdir(outputDir, { recursive: true });

  try {
    const specRaw = await readFile(specPath, "utf8");
    const openApiDoc = parseYaml(specRaw) as OpenAPIObject;

    const context = getZodClientTemplateContext(openApiDoc, {
      groupStrategy: "none",
      withAlias: true,
      shouldExportAllSchemas: true,
      shouldExportAllTypes: true,
      withAllResponses: true,
      withDefaultValues: true,
    });

    const metadataByAlias = buildOperationMetadata(openApiDoc);

    const schemaNames = new Set(Object.keys(context.schemas));
    const servicePrefix = SERVICE_TYPE_PREFIX[service];

    await removeLegacyFile(join(outputDir, "operations.ts"));

    await writeGeneratedFile(
      join(outputDir, "schemas.ts"),
      sanitizeSchemaCode(buildSchemasFile(context)),
    );

    await writeGeneratedFile(
      join(outputDir, "operation-specs.ts"),
      sanitizeSchemaCode(
        buildOperationSpecsFile(context, metadataByAlias, schemaNames, servicePrefix),
      ),
    );

    await writeGeneratedFile(
      join(outputDir, "index.ts"),
      buildIndexFile(servicePrefix),
    );

    await writeMetadataFile(outputDir, service, specPath);

    return {
      service,
      status: "generated",
    };
  } catch (error) {
    return {
      service,
      status: "failed",
      message: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

function buildSchemasFile(context: TemplateContext): string {
  const lines: string[] = [];

  lines.push('import { z } from "zod";');
  lines.push("");

  for (const [name, schema] of Object.entries(context.schemas)) {
    lines.push(`export const ${name} = ${schema};`);
  }

  if (Object.keys(context.schemas).length > 0) {
    lines.push("");
  }

  for (const name of Object.keys(context.schemas)) {
    if (context.emittedType?.[name]) {
      lines.push(`export type ${name} = z.infer<typeof ${name}>;`);
    }
  }

  if (Object.keys(context.schemas).length > 0) {
    lines.push("");
    lines.push("const schemaCollection = {");
    for (const name of Object.keys(context.schemas)) {
      lines.push(`  ${name},`);
    }
    lines.push("} as const;");
    lines.push("");
    lines.push("export const schemas = schemaCollection;");
    lines.push("export type SchemaRegistry = typeof schemas;");
  } else {
    lines.push("");
    lines.push("export const schemas = {} as const;");
    lines.push("export type SchemaRegistry = typeof schemas;");
  }

  return lines.join("\n");
}

function buildOperationSpecsFile(
  context: TemplateContext,
  metadataByAlias: Map<string, OperationMetadata>,
  schemaNames: ReadonlySet<string>,
  servicePrefix: string,
): string {
  const lines: string[] = [];

  lines.push('import { z } from "zod";');
  lines.push('import type { OperationSpecMap } from "../../types";');
  lines.push('import * as schemas from "./schemas";');
  lines.push("");
  lines.push("function defineOperationSpecs<const T extends OperationSpecMap>(specs: T): T {");
  lines.push("  return specs;");
  lines.push("}");
  lines.push("");
  lines.push("export const operationSpecs = defineOperationSpecs({");

  for (const endpoint of context.endpoints) {
    const alias = endpoint.alias;
    const metadata = metadataByAlias.get(alias);
    if (!metadata) {
      continue;
    }

    lines.push(`  ${alias}: {`);
    lines.push(`    alias: "${alias}",`);
    lines.push(`    method: "${endpoint.method}",`);
    lines.push(`    path: "${endpoint.path}",`);
    lines.push(`    pathTemplate: ${JSON.stringify(metadata.pathTemplate)},`);

    if (endpoint.description) {
      lines.push(`    description: ${JSON.stringify(endpoint.description)},`);
    }

    if (endpoint.requestFormat) {
      lines.push(`    requestFormat: "${endpoint.requestFormat}",`);
    }

    const parameterLines = buildParameterLines(
      endpoint.parameters ?? [],
      metadata,
      schemaNames,
    );
    lines.push("    parameters: [");
    if (parameterLines.length > 0) {
      for (const parameterLine of parameterLines) {
        lines.push(parameterLine);
      }
    }
    lines.push("    ] as const,");

    if (metadata.body) {
      const bodyDefinition = buildBodyDefinition(
        endpoint.parameters ?? [],
        metadata.body,
        schemaNames,
      );
      if (bodyDefinition) {
        lines.push(`    body: ${bodyDefinition},`);
      }
    }

    lines.push(
      `    response: ${rewriteSchemaExpression(endpoint.response, schemaNames)},`,
    );

    const errorLines = buildErrorLines(endpoint.errors ?? [], schemaNames);
    lines.push("    errors: [");
    if (errorLines.length > 0) {
      for (const errorLine of errorLines) {
        lines.push(errorLine);
      }
    }
    lines.push("    ] as const,");
    lines.push("  },");
  }

  lines.push("} as const satisfies OperationSpecMap);");
  lines.push("");
  lines.push(
    `export type ${servicePrefix}OperationSpecs = typeof operationSpecs;`,
  );
  lines.push(
    `export type ${servicePrefix}OperationAlias = keyof ${servicePrefix}OperationSpecs;`,
  );

  return lines.join("\n");
}

function buildIndexFile(servicePrefix: string): string {
  return [
    'export * from "./schemas";',
    `export { operationSpecs } from "./operation-specs";`,
    `export type { ${servicePrefix}OperationSpecs, ${servicePrefix}OperationAlias } from "./operation-specs";`,
  ].join("\n");
}

function buildParameterLines(
  parameters: Array<{
    name: string;
    type?: string;
    description?: string;
    schema: string;
  }>,
  metadata: OperationMetadata,
  schemaNames: ReadonlySet<string>,
): string[] {
  const lines: string[] = [];

  for (const parameter of parameters) {
    const location = normalizeParameterLocation(parameter.type);
    if (!location || location === "body") {
      continue;
    }

    const lookupName =
      location === "path" ? sanitizeParameterName(parameter.name, location) : parameter.name;
    const requirement = metadata.parameters.get(
      createParameterKey(location, lookupName),
    );
    const required = requirement?.required ?? false;

    const fieldLines: string[] = [];
    fieldLines.push("{");
    fieldLines.push(`  name: ${JSON.stringify(parameter.name)},`);
    fieldLines.push(`  location: "${location}",`);
    fieldLines.push(`  required: ${required ? "true" : "false"},`);
    if (parameter.description) {
      fieldLines.push(`  description: ${JSON.stringify(parameter.description)},`);
    }
    fieldLines.push(
      `  schema: ${rewriteSchemaExpression(parameter.schema, schemaNames)},`,
    );
    fieldLines.push("},");

    const block = fieldLines.map((line) => `      ${line}`).join("\n");
    lines.push(block);
  }

  return lines;
}

function buildBodyDefinition(
  parameters: Array<{
    name: string;
    type?: string;
    description?: string;
    schema: string;
  }>,
  bodyMetadata: OperationBodyMetadata,
  schemaNames: ReadonlySet<string>,
): string | undefined {
  const bodyParameter = parameters.find((parameter) =>
    normalizeParameterLocation(parameter.type) === "body",
  );

  if (!bodyParameter) {
    return undefined;
  }

  const segments: string[] = [];
  segments.push("{");
  segments.push(`  required: ${bodyMetadata.required ? "true" : "false"},`);
  if (bodyParameter.description ?? bodyMetadata.description) {
    const description = bodyParameter.description ?? bodyMetadata.description ?? "";
    segments.push(`  description: ${JSON.stringify(description)},`);
  }
  segments.push(
    `  schema: ${rewriteSchemaExpression(bodyParameter.schema, schemaNames)},`,
  );
  segments.push(
    `  contentTypes: ${JSON.stringify([...bodyMetadata.contentTypes])} as const,`,
  );
  segments.push("}");

  const block = segments
    .map((line, index) => {
      if (index === 0) {
        return line;
      }
      if (index === segments.length - 1) {
        return `    ${line}`;
      }
      return `      ${line}`;
    })
    .join("\n");

  return block;
}

function buildErrorLines(
  errors: Array<{
    status: number | "default";
    description?: string;
    schema: string;
  }>,
  schemaNames: ReadonlySet<string>,
): string[] {
  const lines: string[] = [];

  for (const error of errors) {
    const errorLines: string[] = [];
    errorLines.push("{");
    if (typeof error.status === "number") {
      errorLines.push(`  status: ${error.status},`);
    } else {
      errorLines.push('  status: "default",');
    }
    if (error.description) {
      errorLines.push(`  description: ${JSON.stringify(error.description)},`);
    }
    errorLines.push(
      `  schema: ${rewriteSchemaExpression(error.schema, schemaNames)},`,
    );
    errorLines.push("},");

    const block = errorLines.map((line) => `      ${line}`).join("\n");
    lines.push(block);
  }

  return lines;
}

function buildOperationMetadata(openApiDoc: OpenAPIObject): Map<string, OperationMetadata> {
  const entries = new Map<string, OperationMetadata>();

  for (const [pathTemplate, pathItemValue] of Object.entries(openApiDoc.paths ?? {})) {
    const pathItem = pathItemValue as PathItemObject;
    const baseParameters = pathItem.parameters ?? [];

    for (const method of HTTP_METHODS) {
      const operation = pathItem[method];
      if (!operation) {
        continue;
      }

      if (operation.deprecated) {
        continue;
      }

      const alias = computeAlias(method, pathTemplate, operation);
      const parameterMap = collectParameters(baseParameters, operation.parameters ?? [], openApiDoc);
      const parameterRequirements = new Map<string, ParameterRequirement>();

      for (const parameter of parameterMap.values()) {
        if (!parameter.in) {
          continue;
        }
        const location = normalizeParameterLocation(parameter.in);
        if (!location || location === "body") {
          continue;
        }
        const sanitizedName = sanitizeParameterName(parameter.name, location);
        parameterRequirements.set(createParameterKey(location, sanitizedName), {
          required:
            location === "path" ? true : Boolean(parameter.required ?? false),
        });
      }

      const requestBody = resolveRequestBody(operation.requestBody, openApiDoc);
      const bodyMetadata = requestBody
        ? {
            required: Boolean(requestBody.required ?? false),
            contentTypes: Array.from(
              new Set(Object.keys(requestBody.content ?? {})),
            ),
            description: requestBody.description,
          }
        : undefined;

      entries.set(alias, {
        pathTemplate,
        parameters: parameterRequirements,
        body: bodyMetadata,
      });
    }
  }

  return entries;
}

function collectParameters(
  pathParameters: ReadonlyArray<ParameterObject | ReferenceObject>,
  operationParameters: ReadonlyArray<ParameterObject | ReferenceObject>,
  doc: OpenAPIObject,
): Map<string, ParameterObject> {
  const map = new Map<string, ParameterObject>();

  for (const parameter of pathParameters) {
    const resolved = resolveParameter(parameter, doc);
    const key = `${resolved.in ?? ""}:${resolved.name}`;
    map.set(key, resolved);
  }

  for (const parameter of operationParameters) {
    const resolved = resolveParameter(parameter, doc);
    const key = `${resolved.in ?? ""}:${resolved.name}`;
    map.set(key, resolved);
  }

  return map;
}

function resolveParameter(
  parameter: ParameterObject | ReferenceObject,
  doc: OpenAPIObject,
): ParameterObject {
  if (isReferenceObject(parameter)) {
    return resolveRef(parameter.$ref, doc) as ParameterObject;
  }
  return parameter;
}

function resolveRequestBody(
  requestBody: OperationObject["requestBody"],
  doc: OpenAPIObject,
): RequestBodyObject | undefined {
  if (!requestBody) {
    return undefined;
  }
  if (isReferenceObject(requestBody)) {
    return resolveRef(requestBody.$ref, doc) as RequestBodyObject;
  }
  return requestBody as RequestBodyObject;
}

function resolveRef(ref: string, doc: OpenAPIObject): unknown {
  if (!ref.startsWith("#/")) {
    throw new Error(`Unsupported ref: ${ref}`);
  }
  const pathSegments = ref
    .slice(2)
    .split("/")
    .map((segment) => segment.replace(/~1/g, "/").replace(/~0/g, "~"));

  let current: unknown = doc;
  for (const segment of pathSegments) {
    if (typeof current !== "object" || current === null) {
      return undefined;
    }
    current = (current as Record<string, unknown>)[segment];
  }
  return current;
}

function computeAlias(
  method: string,
  pathTemplate: string,
  operation: OperationObject,
): string {
  if (operation.operationId) {
    return operation.operationId;
  }
  const sanitizedPath = pathTemplate
    .replace(/[{}]/g, "")
    .split(/\W+/)
    .filter((segment) => segment.length > 0)
    .map((segment) => segment[0]?.toUpperCase() + segment.slice(1))
    .join("");
  return `${method}${sanitizedPath}`;
}

function normalizeParameterLocation(type?: string): "path" | "query" | "header" | "body" | undefined {
  if (!type) {
    return undefined;
  }
  const value = type.toLowerCase();
  if (value === "path" || value === "query" || value === "header" || value === "body") {
    return value;
  }
  if (value === "headers") {
    return "header";
  }
  return undefined;
}

function sanitizeParameterName(name: string, location: string): string {
  if (location !== "path") {
    return name;
  }
  const segments = name
    .split(/[-_]/)
    .filter((segment) => segment.length > 0);
  if (segments.length === 0) {
    return name;
  }
  return segments
    .map((segment, index) =>
      index === 0 ? segment : segment[0]?.toUpperCase() + segment.slice(1),
    )
    .join("");
}

function createParameterKey(location: string, name: string): string {
  return `${location}:${name}`;
}

function rewriteSchemaExpression(
  schema: string,
  schemaNames: ReadonlySet<string>,
): string {
  if (schemaNames.size === 0) {
    return schema;
  }

  const reserved = new Set(["z"]);
  let result = "";
  let token = "";
  let inString: false | "'" | "\"" | "`" = false;
  let escaping = false;

  const flushToken = () => {
    if (!token) {
      return;
    }
    if (schemaNames.has(token) && !reserved.has(token)) {
      result += `schemas.${token}`;
    } else {
      result += token;
    }
    token = "";
  };

  for (const char of schema) {
    if (inString) {
      result += char;
      if (escaping) {
        escaping = false;
        continue;
      }
      if (char === "\\") {
        escaping = true;
        continue;
      }
      if (char === inString) {
        inString = false;
      }
      continue;
    }

    if (char === "'" || char === '"' || char === "`") {
      flushToken();
      inString = char;
      result += char;
      continue;
    }

    if (/[_a-zA-Z0-9]/.test(char)) {
      token += char;
      continue;
    }

    flushToken();
    result += char;
  }

  flushToken();
  return result;
}

function sanitizeSchemaCode(code: string): string {
  const withoutNullEnums = code.replace(/z\.enum\(\[(.*?)\]\)/gs, (match, inner) => {
    if (!/\bnull\b/.test(inner)) {
      return match;
    }
    const values = inner
      .split(",")
      .map((part) => part.trim())
      .filter((part) => part.length > 0 && part !== "null");
    return `z.enum([${values.join(", ")}])`;
  });

  const withLazyAnnotations = withoutNullEnums.replace(
    /const ([A-Z][A-Za-z0-9_]*) = z\.lazy/g,
    "const $1: z.ZodLazy<z.ZodTypeAny> = z.lazy",
  );

  return withLazyAnnotations.replace(/z\.discriminatedUnion\(\s*"[^"]+",\s*\[/g, "z.union([");
}

async function writeGeneratedFile(path: string, contents: string): Promise<void> {
  const formatted = maybePretty(`${FILE_HEADER}\n${contents}`, { filepath: path });
  const normalized = formatted.endsWith("\n") ? formatted : `${formatted}\n`;
  await writeFile(path, normalized, "utf8");
}

async function writeMetadataFile(
  outputDir: string,
  service: Service,
  specPath: string,
): Promise<void> {
  const specHash = await computeFileHash(specPath);
  const metadata = {
    service,
    specPath,
    specHash,
    generatedAt: new Date().toISOString(),
  };
  const metadataPath = join(outputDir, "metadata.json");
  const serialized = `${JSON.stringify(metadata, null, 2)}\n`;
  await writeFile(metadataPath, serialized, "utf8");
}

async function computeFileHash(path: string): Promise<string> {
  const buffer = await readFile(path);
  const hash = createHash("sha256");
  hash.update(buffer);
  return hash.digest("hex");
}

async function removeLegacyFile(path: string): Promise<void> {
  if (await fileExists(path)) {
    await rm(path);
  }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function isReferenceObject(value: unknown): value is ReferenceObject {
  return typeof value === "object" && value !== null && "$ref" in value;
}

await main();
